services:
  # Eclipse Theia IDE Base Service (for image building only)
  # Individual user containers are managed dynamically by the backend
  theia-base:
    build:
      context: ./theia
      dockerfile: Dockerfile
    image: robot-console-theia:latest
    container_name: theia-base
    # This service is only used for building the base image
    # It doesn't run continuously - user containers are managed by backend API
    profiles:
      - build-only
    environment:
      - THEIA_BASE_PORT=${THEIA_BASE_PORT:-3001}
      - THEIA_PROJECT_PATH=${THEIA_PROJECT_PATH:-./projects}
    networks:
      - robot-console-network
    volumes:
      - type: bind
        source: ./projects
        target: /home/project
        bind:
          create_host_path: true

networks:
  robot-console-network:
    driver: bridge
    name: robot-console-network
    external: true

volumes:
  # Persistent storage for user project directories
  # Projects are stored as bind mounts from ./projects to enable
  # direct file access and persistence across container restarts
  # Each user gets their own isolated directory mounted at /home/project
  projects_data:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: ./projects